version: '3.3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'
    volumes:
      - ./public/image:/root/public/image
      - ./app:/root/app
      - ./chat/images:/root/djangotutorial/chat/images